SELECT * FROM TELEFONO
SELECT * FROM MATRICULA
SELECT * FROM ALUMNO
SELECT * FROM FAMILIARES
SELECT * FROM TIPO_PERSONA
SELECT * FROM GRUPO_FAMILIAR
SELECT * FROM PERSONA


SELECT * FROM FN_DIRECTORIO_TELEFONOS('2022',20,21)

CREATE OR REPLACE FUNCTION FN_DIRECTORIO_TELEFONOS(IN_ANIO VARCHAR,IN_CURSO INT,IN_SECCION INT)
RETURNS TABLE(OUT_NOMBRE TEXT,OUT_WHATSAPP JSON,OUT_TELEFONOS JSON)
AS
$$
BEGIN
RETURN QUERY
SELECT CONCAT(PERSONA.PRIMER_NOMBRE,' ',PERSONA.SEGUNDO_NOMBRE,' ',
			  PERSONA.PRIMER_APELLIDO,' ',PERSONA.SEGUNDO_APELLIDO)AS NOMBRE,		 
(SELECT JSON_AGG(JSON_BUILD_OBJECT(
				    'telefonos',TELEFONO.TELEFONO)) AS TELEFONOS FROM TELEFONO
					INNER JOIN TELEFONO_PERSONA ON TELEFONO.COD_TELEFONO=TELEFONO_PERSONA.COD_TELEFONO
 					INNER JOIN PERSONA ON TELEFONO_PERSONA.COD_PERSONA = PERSONA.COD_PERSONA
 					INNER JOIN FAMILIARES ON PERSONA.COD_PERSONA = FAMILIARES.COD_PERSONA
 					INNER JOIN GRUPO_FAMILIAR ON FAMILIARES.COD_GRUPO= GRUPO_FAMILIAR.COD_GRUPO
 					INNER JOIN MATRICULA ON GRUPO_FAMILIAR.COD_GRUPO = MATRICULA.COD_GRUPO
 					WHERE MATRICULA.ANIO = IN_ANIO AND MATRICULA.COD_CURSO=IN_CURSO AND MATRICULA.COD_SECCION =IN_SECCION
 					AND TELEFONO.WHATSAPP=TRUE
 				
)AS NUMEROS_WHATSAPP,
(SELECT JSON_AGG(JSON_BUILD_OBJECT(
				    'telefonos',TELEFONO.TELEFONO)) AS TELEFONOS FROM TELEFONO
					INNER JOIN TELEFONO_PERSONA ON TELEFONO.COD_TELEFONO=TELEFONO_PERSONA.COD_TELEFONO
 					INNER JOIN PERSONA ON TELEFONO_PERSONA.COD_PERSONA = PERSONA.COD_PERSONA
 					INNER JOIN FAMILIARES ON PERSONA.COD_PERSONA = FAMILIARES.COD_PERSONA
 					INNER JOIN GRUPO_FAMILIAR ON FAMILIARES.COD_GRUPO= GRUPO_FAMILIAR.COD_GRUPO
 					INNER JOIN MATRICULA ON GRUPO_FAMILIAR.COD_GRUPO = MATRICULA.COD_GRUPO
 					WHERE MATRICULA.ANIO = IN_ANIO AND MATRICULA.COD_CURSO=IN_CURSO AND MATRICULA.COD_SECCION=IN_SECCION
 					AND TELEFONO.WHATSAPP=FALSE
)AS NUMEROS_TELEFONO
		  			  FROM PERSONA
INNER JOIN TIPO_PERSONA ON PERSONA.COD_TIPO_PERSONA = TIPO_PERSONA.COD_TIPO_PERSONA
INNER JOIN ALUMNOS ON PERSONA.COD_PERSONA = ALUMNOS.COD_PERSONA
WHERE TIPO_PERSONA.COD_TIPO_PERSONA = 4
AND ALUMNOS.COD_ALUMNO IN (SELECT COD_ALUMNO FROM MATRICULA WHERE ANIO = IN_ANIO AND COD_CURSO=IN_CURSO AND MATRICULA.COD_SECCION =IN_SECCION);

END;
$$
LANGUAGE PLPGSQL;

SELECT * FROM MATRICULA
--NOMBRES DE ALUMNOS

SELECT * FROM ALUMNOS
SELECT * FROM EXPEDIENTE
SELECT * FROM GRUPO_FAMILIAR


SELECT * FROM FN_REPORTE_MATRICULA_DIARIA('2022')

CREATE OR REPLACE FUNCTION FN_REPORTE_MATRICULA_DIARIA(IN_ANIO VARCHAR)
RETURNS TABLE (NOMBRE_ALUMNO TEXT,CODIGO_GRUPO INT,COLEGIO_ANTERIOR VARCHAR,CURSO_MATRICULA VARCHAR,FECHA_MATRICULA DATE)
AS
$$
BEGIN
RETURN QUERY
SELECT CONCAT(PERSONA.PRIMER_NOMBRE,' ',PERSONA.SEGUNDO_NOMBRE,' ',
			  PERSONA.PRIMER_APELLIDO,' ',PERSONA.SEGUNDO_APELLIDO)AS NOMBRE,GRUPO_FAMILIAR.COD_GRUPO,
			  COLEGIO.NOMBRE AS COLEGIO_ANTERIOR,CURSOS.NOMBRE AS CURSO_MATRICULADO,
			  MATRICULA.FEC_REGISTRO AS FECHA_MATRICULA
			
 FROM PERSONA
 INNER JOIN ALUMNOS ON PERSONA.COD_PERSONA = ALUMNOS.COD_PERSONA
 INNER JOIN TIPO_PERSONA ON PERSONA.COD_TIPO_PERSONA = TIPO_PERSONA.COD_TIPO_PERSONA
 INNER JOIN GRUPO_FAMILIAR ON ALUMNOS.COD_GRUPO= GRUPO_FAMILIAR.COD_GRUPO
 INNER JOIN MATRICULA ON ALUMNOS.COD_ALUMNO =MATRICULA.COD_ALUMNO
 INNER JOIN EXPEDIENTE ON ALUMNOS.COD_ALUMNO =EXPEDIENTE.COD_ALUMNO
 INNER JOIN COLEGIO ON EXPEDIENTE.COD_COLEGIO= COLEGIO.COD_COLEGIO
 INNER JOIN CURSOS ON MATRICULA.COD_CURSO=CURSOS.COD_CURSO
			  WHERE TIPO_PERSONA.COD_TIPO_PERSONA =4  AND MATRICULA.ANIO=IN_ANIO;
END;
$$
LANGUAGE PLPGSQL;

GROUP BY MATRICULA.FEC_REGISTRO, GRUPO_FAMILIAR.COD_GRUPO,PERSONA.PRIMER_NOMBRE,PERSONA.SEGUNDO_NOMBRE,PERSONA.PRIMER_APELLIDO,
 			PERSONA.SEGUNDO_APELLIDO,EXPEDIENTE.ANIO,COLEGIO.NOMBRE,CURSOS.NOMBRE 

 
 
 
 
SELECT * FROM EXPEDIENTE
SELECT CONCAT(PERSONA.PRIMER_NOMBRE,' ',PERSONA.SEGUNDO_NOMBRE,' ',
			  PERSONA.PRIMER_APELLIDO,' ',PERSONA.SEGUNDO_APELLIDO)AS NOMBRE, 
			  MATRICULA.FEC_REGISTRO,EXTRACT(YEAR FROM EXPEDIENTE.ANIO),
			  COLEGIO.NOMBRE AS COLEGIO,CURSOS.NOMBRE AS CURSO_MATRICULADO,
			  MATRICULA.FEC_REGISTRO AS FECHA_MATRICULA
			  FROM PERSONA
			  INNER JOIN TIPO_PERSONA ON PERSONA.COD_TIPO_PERSONA = TIPO_PERSONA.COD_TIPO_PERSONA
			  INNER JOIN ALUMNOS ON PERSONA.COD_PERSONA = ALUMNOS.COD_PERSONA
			  INNER JOIN MATRICULA ON ALUMNOS.COD_ALUMNO= MATRICULA.COD_ALUMNO
			  INNER JOIN EXPEDIENTE ON ALUMNOS.COD_ALUMNO =EXPEDIENTE.COD_ALUMNO
			  INNER JOIN COLEGIO ON EXPEDIENTE.COD_COLEGIO= COLEGIO.COD_COLEGIO
			  INNER JOIN CURSOS ON MATRICULA.COD_CURSO=CURSOS.COD_CURSO
			  WHERE MATRICULA.ANIO = '2022'
			  
			  
			  INSERT INTO CURSOS 
			  SELECT * FROM CURSOS
			  SELECT * FROM EXPEDIENTE
			  UPDATE EXPEDIENTE
