	SELECT * FROM TIPO_MATRICULA
	SELECT * FROM MATRICULA
	SELECT * FROM EXPEDIENTE
	SELECT * FROM SECCIONES
	SELECT * FROM CURSOS
	
	
	
	ALTER TABLE MATRICULA ADD COLUMN DOC_PENDIENTE BOOLEAN NOT NULL 
	ALTER TABLE MATRICULA ADD COLUMN DOC_DESCRIPCION VARCHAR  
	
	
	INSERT INTO TIPO_MATRICULA(NOMBRE,USR_REGISTRO,FEC_REGISTRO)
				VALUES('COLEGIO','jorgeaguilera.agz@gmail.com',current_date)
				
				
SELECT * FROM FN_TIPOS_MATRICULA()				
CREATE OR REPLACE FUNCTION FN_TIPOS_MATRICULA() RETURNS TABLE(OUT_COD_TIPO INT,OUT_NOMBRE VARCHAR)
AS
$$
BEGIN
RETURN QUERY
SELECT COD_TIPO_MATRICULA, NOMBRE FROM TIPO_MATRICULA;
END;
$$
LANGUAGE PLPGSQL;


SELECT * FROM FN_CURSOS()
CREATE OR REPLACE FUNCTION FN_CURSOS() RETURNS TABLE(OUT_COD_CURSO INT,OUT_NOMBRE VARCHAR,OUT_ESTADO BOOLEAN)
AS
$$
BEGIN
RETURN QUERY
SELECT COD_CURSO,NOMBRE,ESTADO FROM CURSOS
WHERE ESTADO= TRUE
ORDER BY NOMBRE ASC;
END;
$$
LANGUAGE PLPGSQL;


