--PROCEDIMIENTOS ALMACENADOS CONTRATOS Y CLAUSULAS


SELECT * FROM FN_LISTA_CONTRATOS(0)
CREATE OR REPLACE FUNCTION FN_LISTA_CONTRATOS(IN_OFFSET INT)RETURNS TABLE(OUT_NOMBRE VARCHAR, OUT_ESTADO BOOLEAN,OUT_COD_CONTRATO INT)
AS
$$
BEGIN
RETURN QUERY
SELECT NOMBRE,ESTADO,COD_CONTRATO FROM CONTRATOS
LIMIT 10
OFFSET IN_OFFSET;
END;
$$
LANGUAGE PLPGSQL;

SELECT * FROM CONTRATOS
SELECT * FROM CLAUSULAS
SELECT COD_CLAUSULA, NOMBRE, CONTENIDO FROM CLASULA
