--FUNCIONES Y PROCEDIMIENTOS COLEGIOS
SELECT * FROM FN_LISTA_COLEGIOS(0)
CREATE OR REPLACE FUNCTION FN_LISTA_COLEGIOS(IN_OFFSET INT)RETURNS TABLE(OUT_COD_COLEDIO INT, OUT_NOMBRE VARCHAR, 
																		 OUT_ESTADO BOOLEAN,OUT_TOTAL BIGINT)
AS
$$
BEGIN
RETURN QUERY
SELECT COD_COLEGIO,NOMBRE,ESTADO,(SELECT COUNT(COD_COLEGIO) FROM COLEGIO) FROM COLEGIO
OFFSET IN_OFFSET
LIMIT 10;
END;
$$
LANGUAGE PLPGSQL;

CALL SP_NUEVO_COLEGIO('ABELARDO R. FORTIN',true,'jorgeaguilera.agz@gmail.com')
CREATE OR REPLACE PROCEDURE SP_NUEVO_COLEGIO(IN_NOMBRE VARCHAR,IN_ESTADO BOOLEAN,IN_USR_REGISTRO VARCHAR)
AS
$$
BEGIN
INSERT INTO COLEGIO(NOMBRE,ESTADO,USR_REGISTRO,FEC_REGISTRO)
VALUES(UPPER(IN_NOMBRE),IN_ESTADO,IN_USR_REGISTRO,CURRENT_DATE);
	exception 
	   when sqlstate '23505' then 
	      raise exception using hint = 'El colegio ingresado ya existe';
END;
$$
LANGUAGE PLPGSQL;
SELECT * FROM COLEGIO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_COLEGIO(IN_COD_COLEGIO INT, IN_NOMBRE VARCHAR,IN_ESTADO BOOLEAN,IN_USR_REGISTRO VARCHAR)
AS
$$
BEGIN
UPDATE COLEGIO SET NOMBRE= IN_NOMBRE,
				   ESTADO=IN_ESTADO,
				   USR_REGISTRO= IN_USR_REGISTRO
				   WHERE COD_COLEGIO = IN_COD_COLEGIO;
END;
$$
LANGUAGE PLPGSQL;
